services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: statistics-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/statistics"
      ASYNC_DATABASE_URI: "postgresql+asyncpg://admin:admin@db:5432/statistics"
    env_file:
      - dev.env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    container_name: statistics-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=statistics
    ports:
      - "2345:5432"
    env_file:
      - dev.env